name: Script Error Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-script:
    name: Check Script for Errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install accelerate bitsandbytes

      - name: Check script for errors
        run: |
          python -c "import your_script"
